engines:
  structure:
    enabled: false
  duplication:
    enabled: false
  sonar-java:
    enabled: true
    channel: beta
    config:
      charset: iso-8859-1
ratings:
  paths:
    - "**.java"
exclude_paths:
  - "**.js"
  - "**.jsx"
  - "**.rb"
  - "**.py"
